feature: Add 9 years old Casadi MPC implementation, which has the bug in l. 70:
ode_integrator = casadi.SXFunction("f_int",
AttributeError: module 'casadi' has no attribute 'SXFunction'